from typing import List
from pydantic import BaseModel

class SHLProduct(BaseModel):
    id: str
    name: str
    url: str
    type: str
    description: str
    duration: str
    jobLevels: List[str]
    targetRoles: List[str]
    skills: List[str]
    languages: List[str]

shl_products: List[SHLProduct] = [
    SHLProduct(
        id="global-skills-development-report",
        name="Global Skills Development Report",
        url="https://www.shl.com/products/product-catalog/view/global-skills-development-report/",
        type="Ability & Aptitude",
        description="This report is designed to be given to individuals who have completed the Global Skills Assessment (GSA). With coverage across the Great 8 Domains, this measure of self-reported behaviors offers a complete overview of their current skills. Participants receive actionable tips on leveraging their top skill strengths and how they might develop their growth skills.",
        duration="",
        jobLevels=['Director', 'Entry-Level', 'Executive', 'General Population', 'Graduate', 'Manager', 'Mid-Professional', 'Front Line Manager', 'Supervisor'],
        targetRoles=[],
        skills=['Ability & Aptitude', 'Assessment Exercises', 'Biodata & Situational Judgment', 'Competencies', 'Development & 360', 'Personality & Behavior'],
        languages=[]
    ),
    SHLProduct(
        id="net-framework-4-5",
        name=".NET Framework 4.5",
        url="https://www.shl.com/products/product-catalog/view/net-framework-4-5/",
        type="Knowledge & Skills",
        description="The .NET Framework 4.5 test measures knowledge of .NET environment.",
        duration="30 minutes",
        jobLevels=['Professional Individual Contributor', 'Mid-Professional'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="net-mvc-new",
        name=".NET MVC (New)",
        url="https://www.shl.com/products/product-catalog/view/net-mvc-new/",
        type="Knowledge & Skills",
        description="Multi-choice test that measures the knowledge of MVC architecture, validation, security, routing.",
        duration="17 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="net-mvvm-new",
        name=".NET MVVM (New)",
        url="https://www.shl.com/products/product-catalog/view/net-mvvm-new/",
        type="Knowledge & Skills",
        description="Multi-choice test that measures the knowledge of MVVM pattern, data validation, ViewModel communication.",
        duration="5 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="net-wcf-new",
        name=".NET WCF (New)",
        url="https://www.shl.com/products/product-catalog/view/net-wcf-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on WCF architecture, programming model, SOA.",
        duration="11 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="net-wpf-new",
        name=".NET WPF (New)",
        url="https://www.shl.com/products/product-catalog/view/net-wpf-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on WPF, XAML controls, events, layouts.",
        duration="9 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="net-xaml-new",
        name=".NET XAML (New)",
        url="https://www.shl.com/products/product-catalog/view/net-xaml-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on XAML triggers, data binding, custom controls.",
        duration="5 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="java-8-new",
        name="Java 8 (New)",
        url="https://www.shl.com/products/product-catalog/view/java-8-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Java class design, exceptions, generics, collections, concurrency, JDBC.",
        duration="18 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="python-new",
        name="Python (New)",
        url="https://www.shl.com/products/product-catalog/view/python-new/",
        type="Knowledge & Skills",
        description="Multi-choice test that measures the knowledge of Python programming, databases, modules and library.",
        duration="11 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="javascript-new",
        name="JavaScript (New)",
        url="https://www.shl.com/products/product-catalog/view/javascript-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on JavaScript language and front-end development.",
        duration="9 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="reactjs-new",
        name="ReactJS (New)",
        url="https://www.shl.com/products/product-catalog/view/reactjs-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on React APIs, render function, JSX, form validation, styling.",
        duration="10 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="angular-6-new",
        name="Angular 6 (New)",
        url="https://www.shl.com/products/product-catalog/view/angular-6-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Angular 6 data binding, dependency injection, CRUD, routing.",
        duration="11 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="angularjs-new",
        name="AngularJS (New)",
        url="https://www.shl.com/products/product-catalog/view/angularjs-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on AngularJS architecture, forms, directives, controllers, routing.",
        duration="9 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="node-js-new",
        name="Node.js (New)",
        url="https://www.shl.com/products/product-catalog/view/node-js-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Node.js events, streams, file system, error handling, express framework.",
        duration="9 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="expressjs-new",
        name="ExpressJS (New)",
        url="https://www.shl.com/products/product-catalog/view/expressjs-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on routing, error handling, security, middleware in ExpressJS.",
        duration="7 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="kubernetes-new",
        name="Kubernetes (New)",
        url="https://www.shl.com/products/product-catalog/view/kubernetes-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on architecture, cluster and services of Kubernetes.",
        duration="6 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="docker-new",
        name="Docker (New)",
        url="https://www.shl.com/products/product-catalog/view/docker-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Docker container, data management, performance and swarm.",
        duration="10 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="amazon-web-services-aws-development-new",
        name="Amazon Web Services (AWS) Development (New)",
        url="https://www.shl.com/products/product-catalog/view/amazon-web-services-aws-development-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on AWS delivery process, monitoring, security, scalability.",
        duration="6 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="c-programming-new",
        name="C Programming (New)",
        url="https://www.shl.com/products/product-catalog/view/c-programming-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on C programming basics, functions, arrays, file handling.",
        duration="10 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="c-programming-new-4039",
        name="C# Programming (New)",
        url="https://www.shl.com/products/product-catalog/view/c-programming-new-4039/",
        type="Knowledge & Skills",
        description="Multi-choice test on C# structure, functions, collections, OOP, exception handling.",
        duration="9 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="c-programming-new-4122",
        name="C++ Programming (New)",
        url="https://www.shl.com/products/product-catalog/view/c-programming-new-4122/",
        type="Knowledge & Skills",
        description="Multi-choice test on C++ language and standard library.",
        duration="10 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="core-java-advanced-level-new",
        name="Core Java (Advanced Level) (New)",
        url="https://www.shl.com/products/product-catalog/view/core-java-advanced-level-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on advanced Java: generics, collections, threads, concurrency.",
        duration="13 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="core-java-entry-level-new",
        name="Core Java (Entry Level) (New)",
        url="https://www.shl.com/products/product-catalog/view/core-java-entry-level-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on basic Java constructs, OOP, file/exception handling, threads.",
        duration="13 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="spring-new",
        name="Spring (New)",
        url="https://www.shl.com/products/product-catalog/view/spring-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Spring core, AOP, IOC container and transactions.",
        duration="9 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="restful-web-services-new",
        name="RESTful Web Services (New)",
        url="https://www.shl.com/products/product-catalog/view/restful-web-services-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on REST architecture, requests, responses, security, filters.",
        duration="12 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="sql-new",
        name="SQL (New)",
        url="https://www.shl.com/products/product-catalog/view/sql-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on SQL queries, data manipulation, transaction processing.",
        duration="9 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="sql-server-new",
        name="SQL Server (New)",
        url="https://www.shl.com/products/product-catalog/view/sql-server-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on basic SQL queries, tables, filtering, aggregation.",
        duration="11 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="mongodb-new",
        name="MongoDB (New)",
        url="https://www.shl.com/products/product-catalog/view/mongodb-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on MongoDB sharding, replication, indexing, queries.",
        duration="7 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="php-new",
        name="PHP (New)",
        url="https://www.shl.com/products/product-catalog/view/php-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on OOP, programming constructs, web & database handling.",
        duration="8 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="ruby-new",
        name="Ruby (New)",
        url="https://www.shl.com/products/product-catalog/view/ruby-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Ruby strings, collections, OOP, exceptions, DB connectivity.",
        duration="11 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="ruby-on-rails-new",
        name="Ruby on Rails (New)",
        url="https://www.shl.com/products/product-catalog/view/ruby-on-rails-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Rails installation, MVC and programming model.",
        duration="11 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="sap-abap-advanced-level-new",
        name="SAP ABAP (Advanced Level) (New)",
        url="https://www.shl.com/products/product-catalog/view/sap-abap-advanced-level-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on SAP ABAP dictionary, dialog programming, workflows.",
        duration="12 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="salesforce-development-new",
        name="Salesforce Development (New)",
        url="https://www.shl.com/products/product-catalog/view/salesforce-development-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Salesforce platform, design/data models, business logic.",
        duration="15 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="selenium-new",
        name="Selenium (New)",
        url="https://www.shl.com/products/product-catalog/view/selenium-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Selenium IDE, RC, grid, web driver, frameworks.",
        duration="10 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="manual-testing-new",
        name="Manual Testing (New)",
        url="https://www.shl.com/products/product-catalog/view/manual-testing-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on software testing life cycle, test design, test reports.",
        duration="10 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="microservices-new",
        name="Microservices (New)",
        url="https://www.shl.com/products/product-catalog/view/microservices-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Microservices architecture, SOA, patterns.",
        duration="7 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="networking-and-implementation-new",
        name="Networking and Implementation (New)",
        url="https://www.shl.com/products/product-catalog/view/networking-and-implementation-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on networking devices, protocols, routing, implementation.",
        duration="7 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="linux-administration-new",
        name="Linux Administration (New)",
        url="https://www.shl.com/products/product-catalog/view/linux-administration-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Linux OS, system and network administration.",
        duration="10 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="linux-programming-general",
        name="Linux Programming (General)",
        url="https://www.shl.com/products/product-catalog/view/linux-programming-general/",
        type="Knowledge & Skills",
        description="Measures knowledge of programming in a Linux environment: Makefiles, C/C++, debugging.",
        duration="25 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="unix-new",
        name="UNIX (New)",
        url="https://www.shl.com/products/product-catalog/view/unix-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on UNIX commands, file system, shell programming.",
        duration="9 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="shell-scripting-new",
        name="Shell Scripting (New)",
        url="https://www.shl.com/products/product-catalog/view/shell-scripting-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on shell scripting for file manipulation and execution.",
        duration="10 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="git-new",
        name="GIT (New)",
        url="https://www.shl.com/products/product-catalog/view/git-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on how to use GIT for version control.",
        duration="13 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="jenkins-new",
        name="Jenkins (New)",
        url="https://www.shl.com/products/product-catalog/view/jenkins-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Jenkins configuration, plugins, nodes, build jobs.",
        duration="6 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="tableau-new",
        name="Tableau (New)",
        url="https://www.shl.com/products/product-catalog/view/tableau-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Tableau tables, visualizations, calculations, filters.",
        duration="8 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="data-science-new",
        name="Data Science (New)",
        url="https://www.shl.com/products/product-catalog/view/data-science-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on machine learning to analyze data and draw conclusions.",
        duration="14 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="apache-spark-new",
        name="Apache Spark (New)",
        url="https://www.shl.com/products/product-catalog/view/apache-spark-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Spark principles, RDD operations, lineage graphs.",
        duration="8 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="apache-hadoop-new",
        name="Apache Hadoop (New)",
        url="https://www.shl.com/products/product-catalog/view/apache-hadoop-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Hadoop concepts, commands, HDFS, MapReduce.",
        duration="7 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="apache-kafka-new",
        name="Apache Kafka (New)",
        url="https://www.shl.com/products/product-catalog/view/apache-kafka-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Kafka architecture, components, clusters, tuning.",
        duration="6 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="cloud-computing-new",
        name="Cloud Computing (New)",
        url="https://www.shl.com/products/product-catalog/view/cloud-computing-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on cloud computing concepts, service models, virtualization.",
        duration="8 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="cyber-risk-new",
        name="Cyber Risk (New)",
        url="https://www.shl.com/products/product-catalog/view/cyber-risk-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on cyber risk management, system/application security.",
        duration="9 minutes",
        jobLevels=['Manager', 'Mid-Professional', 'Professional Individual Contributor', 'Supervisor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="computer-science-new",
        name="Computer Science (New)",
        url="https://www.shl.com/products/product-catalog/view/computer-science-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on OS, computer architecture, DBMS, networks basics.",
        duration="12 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="programming-concepts",
        name="Programming Concepts",
        url="https://www.shl.com/products/product-catalog/view/programming-concepts/",
        type="Knowledge & Skills",
        description="Measures knowledge of core programming concepts valid across languages.",
        duration="25 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="r-programming-new",
        name="R Programming (New)",
        url="https://www.shl.com/products/product-catalog/view/r-programming-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on R programming and its application in statistics.",
        duration="13 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="ios-development-new",
        name="iOS Development (New)",
        url="https://www.shl.com/products/product-catalog/view/ios-development-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Objective C, NSObject, iOS fundamentals, UI design.",
        duration="7 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="android-development-new",
        name="Android Development (New)",
        url="https://www.shl.com/products/product-catalog/view/android-development-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on UI components, services, animation, security testing.",
        duration="7 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="htmlcss-new",
        name="HTML/CSS (New)",
        url="https://www.shl.com/products/product-catalog/view/htmlcss-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on HTML for UI and CSS to stylize it.",
        duration="12 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="html5-new",
        name="HTML5 (New)",
        url="https://www.shl.com/products/product-catalog/view/html5-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on HTML5 and its application in UI creation.",
        duration="11 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="css3-new",
        name="CSS3 (New)",
        url="https://www.shl.com/products/product-catalog/view/css3-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on CSS3 and its application in styling web documents.",
        duration="8 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="jquery-new",
        name="jQuery (New)",
        url="https://www.shl.com/products/product-catalog/view/jquery-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on jQuery events, effects, animation, UI, AJAX.",
        duration="10 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="oracle-plsql-new",
        name="Oracle PL/SQL (New)",
        url="https://www.shl.com/products/product-catalog/view/oracle-plsql-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on SQL queries, relational DB concepts, PL/SQL.",
        duration="11 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="oracle-dba-advanced-level-new",
        name="Oracle DBA (Advanced Level) (New)",
        url="https://www.shl.com/products/product-catalog/view/oracle-dba-advanced-level-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on Oracle DB architecture, backup/recovery, network config.",
        duration="12 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="occupational-personality-questionnaire-opq32r",
        name="Occupational Personality Questionnaire OPQ32r",
        url="https://www.shl.com/products/product-catalog/view/occupational-personality-questionnaire-opq32r/",
        type="Personality & Behavior",
        description="SHL's most widely used measure of workplace behavioural style, covering 32 dimensions of personality relevant to job performance.",
        duration="25 minutes",
        jobLevels=['Professional Individual Contributor', 'Supervisor', 'Mid-Professional', 'Front Line Manager', 'General Population', 'Graduate', 'Manager', 'Director', 'Executive'],
        targetRoles=[],
        skills=['Personality & Behavior'],
        languages=['English International', 'English (USA)']
    ),
    SHLProduct(
        id="opq-universal-competency-report-2-0",
        name="OPQ Universal Competency Report 2.0",
        url="https://www.shl.com/products/product-catalog/view/opq-universal-competency-report-2-0/",
        type="Personality & Behavior",
        description="OPQ report based on the Universal Competency Framework, outlining how behavior impacts competencies.",
        duration="",
        jobLevels=['Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor', 'Supervisor', 'Director', 'Executive', 'Front Line Manager', 'General Population'],
        targetRoles=[],
        skills=['Personality & Behavior'],
        languages=[]
    ),
    SHLProduct(
        id="opq-leadership-report",
        name="OPQ Leadership Report",
        url="https://www.shl.com/products/product-catalog/view/opq-leadership-report/",
        type="Personality & Behavior",
        description="OPQ report providing detailed analysis of leadership potential based on SHL's Leadership Model.",
        duration="",
        jobLevels=['Director', 'Executive', 'Manager', 'Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Personality & Behavior'],
        languages=['English International', 'English (USA)']
    ),
    SHLProduct(
        id="opq-mq-sales-report",
        name="OPQ MQ Sales Report",
        url="https://www.shl.com/products/product-catalog/view/opq-mq-sales-report/",
        type="Personality & Behavior",
        description="OPQ report summarizing an individual's natural style critical to sales success, optionally combined with the Motivation Questionnaire.",
        duration="",
        jobLevels=['Director', 'Executive', 'Front Line Manager', 'General Population', 'Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor', 'Supervisor'],
        targetRoles=[],
        skills=['Personality & Behavior'],
        languages=['English International', 'English (USA)']
    ),
    SHLProduct(
        id="sales-transformation-report-individual-contributor",
        name="Sales Transformation 1.0 - Individual Contributor",
        url="https://www.shl.com/products/product-catalog/view/sales-transformation-report-individual-contributor/",
        type="Personality & Behavior",
        description="OPQ-based report measuring a salesperson's ability to sell well in a digital-first environment.",
        duration="",
        jobLevels=['Front Line Manager', 'General Population', 'Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor', 'Supervisor'],
        targetRoles=[],
        skills=['Personality & Behavior'],
        languages=[]
    ),
    SHLProduct(
        id="salestransformationreport2-0-individualcontributor",
        name="Sales Transformation 2.0 - Individual Contributor",
        url="https://www.shl.com/products/product-catalog/view/salestransformationreport2-0-individualcontributor/",
        type="Personality & Behavior",
        description="OPQ-based report measuring a salesperson's ability to sell well in a digital-first environment (2.0).",
        duration="",
        jobLevels=['Front Line Manager', 'General Population', 'Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor', 'Supervisor'],
        targetRoles=[],
        skills=['Personality & Behavior'],
        languages=[]
    ),
    SHLProduct(
        id="dependability-and-safety-instrument-dsi",
        name="Dependability and Safety Instrument (DSI)",
        url="https://www.shl.com/products/product-catalog/view/dependability-and-safety-instrument-dsi/",
        type="Personality & Behavior",
        description="Short pre-screening tool for entry-level roles, identifying dependability/reliability and low counter-productive work behavior risk.",
        duration="10 minutes",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Personality & Behavior'],
        languages=['English International', 'English (USA)']
    ),
    SHLProduct(
        id="safety-and-dependability-focus-8-0",
        name="Manufac. & Indust. - Safety & Dependability 8.0",
        url="https://www.shl.com/products/product-catalog/view/safety-and-dependability-focus-8-0/",
        type="Personality & Behavior",
        description="Manufacturing & Industrial Safety & Dependability Focus 8.0 assessment measuring behaviors underlying safe performance in industrial settings.",
        duration="16 minutes",
        jobLevels=['Entry-Level', 'Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Personality & Behavior'],
        languages=['English (USA)', 'German', 'Latin American Spanish', 'French', 'English International', 'Chinese Simplified', 'Italian', 'Japanese']
    ),
    SHLProduct(
        id="workplace-health-and-safety-new",
        name="Workplace Health and Safety (New)",
        url="https://www.shl.com/products/product-catalog/view/workplace-health-and-safety-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on first aid, emergency safety, cleanliness and hygiene.",
        duration="9 minutes",
        jobLevels=['Entry-Level', 'Graduate', 'Manager', 'Supervisor', 'Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="hipaa-security",
        name="HIPAA (Security)",
        url="https://www.shl.com/products/product-catalog/view/hipaa-security/",
        type="Knowledge & Skills",
        description="Measures knowledge of compliance with HIPAA Security and Electronic Signature Standards.",
        duration="15 minutes",
        jobLevels=['Front Line Manager', 'Manager'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="medical-terminology-new",
        name="Medical Terminology (New)",
        url="https://www.shl.com/products/product-catalog/view/medical-terminology-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on medical terms and abbreviations related to body, diseases, diagnosis.",
        duration="3 minutes",
        jobLevels=['Graduate', 'Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="microsoft-word-365-essentials-new",
        name="Microsoft Word 365 - Essentials (New)",
        url="https://www.shl.com/products/product-catalog/view/microsoft-word-365-essentials-new/",
        type="Knowledge & Skills",
        description="Simulation evaluating ability to perform operations in Microsoft Word.",
        duration="25 minutes",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Knowledge & Skills', 'Simulations'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="microsoft-word-365-new",
        name="Microsoft Word 365 (New)",
        url="https://www.shl.com/products/product-catalog/view/microsoft-word-365-new/",
        type="Simulations",
        description="Simulation evaluating ability to perform operations in Microsoft Word.",
        duration="35 minutes",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Simulations', 'Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="microsoft-excel-365-new",
        name="Microsoft Excel 365 (New)",
        url="https://www.shl.com/products/product-catalog/view/microsoft-excel-365-new/",
        type="Knowledge & Skills",
        description="Simulation evaluating ability to perform operations in MS Excel.",
        duration="35 minutes",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Knowledge & Skills', 'Simulations'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="microsoft-excel-365-essentials-new",
        name="Microsoft Excel 365 - Essentials (New)",
        url="https://www.shl.com/products/product-catalog/view/microsoft-excel-365-essentials-new/",
        type="Knowledge & Skills",
        description="Simulation evaluating ability to perform operations in MS Excel.",
        duration="30 minutes",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Knowledge & Skills', 'Simulations'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="ms-excel-new",
        name="MS Excel (New)",
        url="https://www.shl.com/products/product-catalog/view/ms-excel-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on using MS Excel to maintain, organize, analyze, present numeric data.",
        duration="6 minutes",
        jobLevels=['Entry-Level', 'Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor', 'Supervisor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)', 'Spanish', 'French', 'Portuguese (Brazil)']
    ),
    SHLProduct(
        id="ms-word-new",
        name="MS Word (New)",
        url="https://www.shl.com/products/product-catalog/view/ms-word-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on using MS Word to record and save textual information.",
        duration="4 minutes",
        jobLevels=['Professional Individual Contributor', 'Supervisor', 'Mid-Professional', 'Entry-Level', 'Graduate', 'Manager'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['Spanish', 'French', 'Portuguese (Brazil)', 'English (USA)']
    ),
    SHLProduct(
        id="ms-powerpoint-new",
        name="MS PowerPoint (New)",
        url="https://www.shl.com/products/product-catalog/view/ms-powerpoint-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on MS PowerPoint toolbars, slide layouts, animation.",
        duration="4 minutes",
        jobLevels=['Entry-Level', 'Front Line Manager', 'Graduate', 'Mid-Professional', 'Professional Individual Contributor', 'Supervisor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)', 'French', 'Spanish', 'Portuguese (Brazil)']
    ),
    SHLProduct(
        id="financial-accounting-new",
        name="Financial Accounting (New)",
        url="https://www.shl.com/products/product-catalog/view/financial-accounting-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on posting journal entries, assets/liabilities, financial ratios.",
        duration="9 minutes",
        jobLevels=['Entry-Level', 'Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor', 'Supervisor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="basic-statistics-new",
        name="Basic Statistics (New)",
        url="https://www.shl.com/products/product-catalog/view/basic-statistics-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on statistical methods, probability, distributions, testing.",
        duration="10 minutes",
        jobLevels=['Graduate', 'Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="graduate-scenarios",
        name="Graduate Scenarios",
        url="https://www.shl.com/products/product-catalog/view/graduate-scenarios/",
        type="Biodata & Situational Judgment",
        description="Test of Managerial Judgement designed for graduates with limited work experience, using hypothetical scenarios.",
        duration="Untimed",
        jobLevels=['Manager', 'Mid-Professional', 'Professional Individual Contributor', 'Graduate'],
        targetRoles=[],
        skills=['Biodata & Situational Judgment'],
        languages=['English International']
    ),
    SHLProduct(
        id="executive-scenarios",
        name="Executive Scenarios",
        url="https://www.shl.com/products/product-catalog/view/executive-scenarios/",
        type="Biodata & Situational Judgment",
        description="Test of Managerial Judgement designed for executives with significant work experience, using hypothetical scenarios.",
        duration="Untimed",
        jobLevels=['Director', 'Executive', 'Manager'],
        targetRoles=[],
        skills=['Biodata & Situational Judgment'],
        languages=['Italian', 'English (USA)', 'English International', 'Korean']
    ),
    SHLProduct(
        id="management-scenarios",
        name="Management Scenarios",
        url="https://www.shl.com/products/product-catalog/view/management-scenarios/",
        type="Biodata & Situational Judgment",
        description="Test of Managerial Judgement using hypothetical scenarios for managers.",
        duration="Untimed",
        jobLevels=['Front Line Manager', 'Manager', 'Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Biodata & Situational Judgment'],
        languages=['Italian', 'English International', 'Korean', 'Arabic']
    ),
    SHLProduct(
        id="global-skills-assessment",
        name="Global Skills Assessment",
        url="https://www.shl.com/products/product-catalog/view/global-skills-assessment/",
        type="Competencies",
        description="Global Skills Assessment (GSA) measures 96 discrete skills/behaviors aligned to SHL's Universal Competency Framework (UCF).",
        duration="16 minutes",
        jobLevels=[],
        targetRoles=[],
        skills=['Competencies', 'Knowledge & Skills'],
        languages=['English International', 'English (USA)']
    ),
    SHLProduct(
        id="shl-verify-interactive-g",
        name="SHL Verify Interactive G+",
        url="https://www.shl.com/products/product-catalog/view/shl-verify-interactive-g/",
        type="Ability & Aptitude",
        description="General cognitive ability test generating scores for Deductive, Inductive and Numerical Reasoning plus a general ability score.",
        duration="36 minutes",
        jobLevels=['Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Ability & Aptitude'],
        languages=['English (USA)', 'English International']
    ),
    SHLProduct(
        id="shl-verify-interactive-numerical-reasoning",
        name="SHL Verify Interactive – Numerical Reasoning",
        url="https://www.shl.com/products/product-catalog/view/shl-verify-interactive-numerical-reasoning/",
        type="Ability & Aptitude",
        description="Assesses how candidates comprehend numerical information in various formats.",
        duration="20 minutes",
        jobLevels=['Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Ability & Aptitude', 'Simulations'],
        languages=['English (USA)', 'English International']
    ),
    SHLProduct(
        id="shl-verify-interactive-deductive-reasoning",
        name="SHL Verify Interactive – Deductive Reasoning",
        url="https://www.shl.com/products/product-catalog/view/shl-verify-interactive-deductive-reasoning/",
        type="Ability & Aptitude",
        description="Measures ability to draw logical conclusions and identify strengths/weaknesses of arguments.",
        duration="20 minutes",
        jobLevels=['Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Ability & Aptitude', 'Simulations'],
        languages=['English (USA)', 'English International']
    ),
    SHLProduct(
        id="shl-verify-interactive-inductive-reasoning",
        name="SHL Verify Interactive - Inductive Reasoning",
        url="https://www.shl.com/products/product-catalog/view/shl-verify-interactive-inductive-reasoning/",
        type="Ability & Aptitude",
        description="Evaluates ability to identify specific patterns and generalize to broader contexts.",
        duration="20 minutes",
        jobLevels=['Professional Individual Contributor', 'Graduate', 'Manager', 'Mid-Professional'],
        targetRoles=[],
        skills=['Ability & Aptitude', 'Simulations'],
        languages=['English (USA)', 'English International']
    ),
    SHLProduct(
        id="smart-interview-live-coding",
        name="Smart Interview Live Coding",
        url="https://www.shl.com/products/product-catalog/view/smart-interview-live-coding/",
        type="Knowledge & Skills",
        description="Real-time online coding interview with compiler interface, supporting many technical roles.",
        duration="Variable",
        jobLevels=['Graduate', 'Manager', 'Mid-Professional', 'Professional Individual Contributor', 'Entry-Level'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="svar-spoken-english-us-new",
        name="SVAR - Spoken English (US) (New)",
        url="https://www.shl.com/products/product-catalog/view/svar-spoken-english-us-new/",
        type="Simulations",
        description="Automated spoken English test measuring fluency, pronunciation, listening, vocabulary, grammar.",
        duration="-",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Simulations'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="svar-spoken-english-u-k",
        name="SVAR - Spoken English (U.K.)",
        url="https://www.shl.com/products/product-catalog/view/svar-spoken-english-u-k/",
        type="Simulations",
        description="Automated spoken English test (UK accent).",
        duration="-",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Simulations'],
        languages=['English International']
    ),
    SHLProduct(
        id="svar-spoken-english-aus",
        name="SVAR - Spoken English (AUS)",
        url="https://www.shl.com/products/product-catalog/view/svar-spoken-english-aus/",
        type="Simulations",
        description="Automated spoken English test (Australian accent).",
        duration="-",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Simulations'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="svar-spoken-english-indian-accent-new",
        name="SVAR - Spoken English (Indian Accent) (New)",
        url="https://www.shl.com/products/product-catalog/view/svar-spoken-english-indian-accent-new/",
        type="Simulations",
        description="Automated spoken English test (Indian accent).",
        duration="-",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Simulations'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="contact-center-call-simulation-new",
        name="Contact Center Call Simulation (New)",
        url="https://www.shl.com/products/product-catalog/view/contact-center-call-simulation-new/",
        type="Simulations",
        description="Simulation measuring ability to handle customer concerns over a call using process documents; also measures typing/documentation skills.",
        duration="15 minutes",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Simulations'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="customer-service-phone-simulation",
        name="Customer Service Phone Simulation",
        url="https://www.shl.com/products/product-catalog/view/customer-service-phone-simulation/",
        type="Biodata & Situational Judgment",
        description="Contact center simulation for entry-level positions handling customer calls.",
        duration="20 minutes",
        jobLevels=[],
        targetRoles=[],
        skills=['Biodata & Situational Judgment', 'Simulations'],
        languages=['English (USA)', 'English International']
    ),
    SHLProduct(
        id="entry-level-customer-serv-retail-and-contact-center",
        name="Entry Level Customer Serv-Retail & Contact Center",
        url="https://www.shl.com/products/product-catalog/view/entry-level-customer-serv-retail-and-contact-center/",
        type="Personality & Behavior",
        description="Precise Fit solution for entry-level customer service positions in retail/contact center.",
        duration="19 minutes",
        jobLevels=['Entry-Level'],
        targetRoles=[],
        skills=['Personality & Behavior', 'Competencies'],
        languages=['English (USA)']
    ),
    SHLProduct(
        id="enterprise-java-beans-new",
        name="Enterprise Java Beans (New)",
        url="https://www.shl.com/products/product-catalog/view/enterprise-java-beans-new/",
        type="Knowledge & Skills",
        description="Multi-choice test on enterprise Java beans (EJB), transactions and concurrency.",
        duration="4 minutes",
        jobLevels=['Mid-Professional', 'Professional Individual Contributor'],
        targetRoles=[],
        skills=['Knowledge & Skills'],
        languages=['English (USA)']
    ),
]
